default: &default
  adapter: postgresql
  encoding: unicode
  database: otprime-store_development
  username: postgres
  password: postgres
  host: localhost
  port: 5434

development:
  <<: *default

test:
  <<: *default
  database: otprime-store_test

production:
  <<: *default
  database: otprime-store_production
